# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-SafePnotes
version:      0.01
version_from: lib/Apache2/SafePnotes.pm
installdirs:  site
requires:
    mod_perl2:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
